#!/bin/bash
################################################################################
# cmbackup - Bash script to hot backup and hot restore Zimbra Collaboration
#            Suite Opensource
#
# Copyright (C) 2021 Lucas Costa Beyeler <lucas.costab@outlook.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
################################################################################
# zmbkpose:
#
# 26/10/2010 - Version 1.0.5 - By Alan Nikitiuk Milani
#                              <alan.milani@4linux.com.br>
#                              <niki.milani@gmail.com>
#
#                              Bruno Gurgel
#                              <bruno@4linux.com.br>
#                              <bruno.gurgel@gmail.com>
#
# 24/05/2012 - Version 2.0 Beta - By William Felipe Welter
#                                 <william.welter@4linux.com.br>
#                                 <wfelipew@gmail.com>
################################################################################
# zmbackup:
#
# 06/02/2021 - Version 1.2.6  - By The Zimbra Community & Lucas Costa Beyeler
#                               <lucas.costab@outlook.com>
################################################################################
# cmbackup:
#
# 20/09/2023 - Version 1.2.8  - By The Carbonio Community & Anahuac Gil
#                               <anahuac@anahuac.eu>
# 04/10/2024 - Version 1.2.9  - By The Carbonio Community & Anahuac Gil
# 30/09/2026 - Version 1.3.0  - Enhancements & Z2C architecture integrations
#                               by kit400 <kit400@users.noreply.github.com>
################################################################################
# parallel:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#  ;login: The USENIX Magazine, February 2011:42-47.
#
################################################################################
# LOADING CMBACKUP LIBRARIES
################################################################################
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CMBKP_LIB_DIR="/usr/local/lib/cmbackup/bash"
if [ ! -d "$CMBKP_LIB_DIR" ]; then
  if [ -d "$SCRIPT_DIR/lib/bash" ]; then
    CMBKP_LIB_DIR="$SCRIPT_DIR/lib/bash"
  elif [ -d "$SCRIPT_DIR/../lib/bash" ]; then
    CMBKP_LIB_DIR="$SCRIPT_DIR/../lib/bash"
  fi
fi

source "$CMBKP_LIB_DIR/HelpAction.sh"
source "$CMBKP_LIB_DIR/MiscAction.sh"
source "$CMBKP_LIB_DIR/NotifyAction.sh"
source "$CMBKP_LIB_DIR/ParallelAction.sh"
source "$CMBKP_LIB_DIR/ListAction.sh"
source "$CMBKP_LIB_DIR/BackupAction.sh"
source "$CMBKP_LIB_DIR/RestoreAction.sh"
source "$CMBKP_LIB_DIR/DeleteAction.sh"
source "$CMBKP_LIB_DIR/MigrationAction.sh"
source "$CMBKP_LIB_DIR/TableHelper.sh"
source "$CMBKP_LIB_DIR/SessionAction.sh"

################################################################################
# CMBACKUP MAIN CODE
################################################################################
# Parse global options (--dry-run, --since, --config)
ARGS=()
export DRY_RUN="FALSE"
export SINCE_DATE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      export DRY_RUN="TRUE"
      shift
      ;;
    --since)
      export SINCE_DATE="$2"
      shift 2
      ;;
    --config)
      export CMBACKUP_CONF="$2"
      shift 2
      ;;
    *)
      ARGS+=("$1")
      shift
      ;;
  esac
done
set -- "${ARGS[@]}"

load_config
validate_config
export_function
export_vars
constant
case "$1" in
  "-f"|"--full" )
    checkpid
    case "$2" in
      "-dl"|"--distributionlist" )
        sessionvars "$2"
        create_temp
        backup_main "$DLOBJECT" "$DLFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-al"|"--alias" )
        sessionvars "$2"
        create_temp
        backup_main "$ALOBJECT" "$ALFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-ldp"|"--ldap" )
        sessionvars "$2"
        create_temp
        backup_main "$ACOBJECT" "$ACFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-m"|"--mail" )
        sessionvars "$2"
        create_temp
        backup_main "$ACOBJECT" "$ACFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-sig"|"--signature" )
        sessionvars "$2"
        create_temp
        backup_main "$SIOBJECT" "$SIFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      * )
        sessionvars "$1"
        create_temp
        if [[ "$2" == *"@"* ]]; then
          backup_main "$ACOBJECT" "$ACFILTER" "-a" "$2"
        else
          backup_main "$ACOBJECT" "$ACFILTER" "$2" "$3"
        fi
        rm -rf "$PID"
      ;;
    esac
  ;;
  "-i"|"--incremental" )
    sessionvars "$1" 'TRUE'
    checkpid
    create_temp
    case "$2" in
      "-a"|"--account"|"-d"|"--domain" )
        backup_main "$ACOBJECT" "$ACFILTER" "$2" "$3"
      ;;
      * )
        if [[ "$2" == *"@"* ]]; then
          backup_main "$ACOBJECT" "$ACFILTER" "-a" "$2"
        else
          backup_main "$ACOBJECT" "$ACFILTER" "$2" "$3"
        fi
      ;;
    esac
    rm -rf "$PID"
  ;;
  "-l"|"--list" )
    list_sessions "$2"
  ;;
  "-r"|"--restore" )
    create_temp
    checkpid
    case "$2" in
      "-dl"|"--distributionlist"|"-ldp"|"--ldap"|"-al"|"--alias"|"-sig"|"--signature")
        case "$3" in
          "-a"|"--account"|"-d"|"--domain")
            restore_main_ldap "$4" "$5"
          ;;
          * )
            restore_main_ldap "$3" "$4"
          ;;
        esac
        rm -rf "$PID"
      ;;
      "-m"|"--mail" )
        restore_main_mailbox "$3" "$4" "$5"
        rm -rf "$PID"
      ;;
      "-ro"|"--restoreOnAccount" )
        if [ -z "$4" ] || [ -z "$5" ]; then
          show_help
          printf "\n\nError! Please inform the account that should be restored, and when the restore should be placed.\n\n"
          exit 2
        else
          constant
          restore_main_mailbox "$3" "$4" "$5"
          rm -rf "$PID"
        fi
      ;;
      * )
        if [[ "$2" == "full"* || "$2" == "inc"* ]]; then
          constant
          restore_main_ldap "$2" "$3" "$4"
          restore_main_mailbox "$2" "$3" "$4"
          rm -rf "$PID"
        else
          show_help
          printf "\n\nError! Invalid parameters for restore\n"
        fi
      ;;
    esac
  ;;
  "-d"|"--delete" )
    if [ -z "$2" ]; then
      show_help
      printf "\n\nError! Please inform the session that should be deleted\n\n"
    else
      checkpid
      delete_one "$2"
      rm -rf "$PID"
    fi
  ;;
  "-hp"|"--housekeep")
    checkpid
    delete_old
    clean_empty
    rm -rf "$PID"
  ;;
  "-t"|"--truncate")
    if [ -n "$2" ] && [ "--force-clean" == "$2" ]; then
      checkpid
      leeroy_jenkins
      clean_empty
      rm -rf "$PID"
    else
      echo "This action is irreversible - Use the option --force-clean to override this message"
    fi
  ;;
  "-c"|"--verify" )
    audit_mailboxes "$2"
  ;;
  "-h"|"--help" )
    show_help
  ;;
  "-v"|"--version" )
    echo "cmbackup version: 1.3.0"
  ;;
  "-m"|"--migrate" )
    checkpid
    migration
    rm -rf "$PID"
  ;;
  * )
    show_help
    printf "\n\nError! Incorrect options\n\n"
  ;;
esac
exit 0
